[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "9CtJ2mHpsNMPPCpEsmRTYDhbZTACFpD2pMFFJiT13qfG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tsmboa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
